#!/usr/bin/env bash
# script that configures a new Ubuntu machine

sudo apt -y update
sudo apt -y install nginx
sudo sed -i '/listen 80 default_server;/ a \\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
