#!/usr/bin/env bash
# installs haproxy and configures it
sudo apt -y update
sudo apt -y install haproxy

echo "
frontend web-frontend
   bind *:80
   mode http
   default_backend web-backend

backend web-backend
   mode http
   balance roundrobin
   server 113851-web-01 54.144.131.23:80 check
   server 113851-web-02 34.207.221.231:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo chmod +x /etc/init.d/haproxy
sudo service haproxy restart
