#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour=0
minutes=0
echo "Hour: $hour"
while [ $((hour++)) -le 12 ]
do
	minutes=0
	while [ $((minutes++)) -lt 59 ]
	do
		echo "$minutes"
	done
	if [[ $hour -lt 13 ]];then
		echo "Hour: $hour"
	fi
done
